name: 29934_deploy
on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["29934_test"]
    types: [completed]

permissions:
  actions: read
  contents: read
  packages: write
  
jobs:
  build_and_push:
    # skripta se zazene samo ce se je tset uspesno zakljucil
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Prenos artefakta
        uses: actions/download-artifact@v4
        with:
          name: preverjanje-napak
          run-id: ${{ github.event.workflow_run.id }} # povezava na id specificnega zagona testov
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: temp_artifact
      
      - name: Kontrola napak
        run: |
          if [ -s napaka.txt ]; then
            echo "Najdena napaka v artefaktu"
            exit 1
          else
            echo "Artefakt je prazen"
          fi
      
      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
         # podatki za prijavo so shranjeni v GitHub secrets
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Gradnja in potisk slike
        run: |
          # prisilno onemogocimo Buildx za celotno sejo
          export DOCKER_BUILDX=off
          export DOCKER_BUILDKIT=0
          
          # gradnja z uporabo klasicnega motorja
          docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/29934-projekt:latest .
          
          # potisk na DockerHub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/29934-projekt:latest
          
