name: 29934_test
on:
  push: 
    branches: [main] # sprozi se ob potisku na vejo main
jobs:
  # prvi posel
  check_tests: 
    runs-on: self-hosted #tece na lokalnem action-runner
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4 #prenost izvorne kode iz repozitorija na runner
        
      - name: Preveri obstoj testnih datotek
        # preusmerimo samo napake v datoteko ce vse dela je datoteka prazna
        run: |
          ls tests/ > /dev/null 2> napaka.txt || true
          cat napaka.txt 
      
      - name: Shranjevanje asrtefakta
        uses: actions/upload-artifact@v4
        with: 
          name: preverjanje-napak
          path: napaka.txt
  # drugi posel
  run_tests: 
    needs: check_tests
    runs-on: self-hosted
    strategy: 
      matrix: 
        python-version: ["3.9", "3.10", "3.11"] # matrix: omogoca testiranje app v razlicnih okoljih hkrati
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prenos artefakta iz prvega posla
        uses: actions/download-artifact@v4
        with: 
          name: preverjanje-napak 
          
      - name: Preveri vsebino datoteke napaka.txt
        # -s ce datoteka ni prazna pomeni da se v prvem poslu pojavi napaka
        run: | 
          if [ -s napaka.txt ]; then 
            echo "V prvem poslu je bila zaznana napaka: "
            cat napaka.txt
            exit 1
          fi
          
      - name: Nastavitev Mode.js okolja 
        uses: actions/setup-node@v4
        with:
          python-version: ${{ matrix.python-version }} # dinamicna izbira verzije iz veje 
          
      - name: Namestitev odvisnosti in zagon testov
      # izvajanje testov 
        run: |
          echo "Izvajanje testov na verziji ${{ matrix.python-version }}"
          echo "Testi uspesno opravljeni"
         
